#index:
#    path: /
#    controller: App\Controller\DefaultController::index


index:
    path: /
    controller: App\Controller\HeroController::index

heros:
    path: /heros
    controller: App\Controller\HeroController::index

test456sasd:
  path: /test456
  controller: App\Controller\HeroController::index
  methods: GET|HEAD
