#index:
#    path: /
#    controller: App\Controller\DefaultController::index


index:
    path: /
    controller: App\Controller\HeroController::index

heros:
    path: /heros
    controller: App\Controller\HeroController::index

decrease:
  path: /hero/decrease
  controller: App\Controller\HeroController::decrease
  # methods: GET|PATCH|POST|HEAD
  schemes: [http]


