#index:
#    path: /
#    controller: App\Controller\DefaultController::index


index:
    path: /
    controller: App\Controller\HeroController::index

heros:
    path: /hero/list
    controller: App\Controller\HeroController::index

heroCreate:
    path: /hero/create
    controller: App\Controller\HeroController::create

heroGet:
    path: /hero/get/{id}
    controller: App\Controller\HeroController::get

heroUpdate:
    path: /hero/update/{id}
    controller: App\Controller\HeroController::update

heroDelete:
    path: /hero/delete/{id}
    controller: App\Controller\HeroController::delete

decrease:
  path: /hero/decrease
  controller: App\Controller\HeroController::decrease
  # methods: GET|PATCH|POST|HEAD
  schemes: [http]

getHeroClass:
  path: /hero/getClass
  controller: App\Controller\HeroController::getClass
  # methods: GET|PATCH|POST|HEAD
  schemes: [http]


